### ISSUE TITLE
Unable to get started using example code in the readme

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignal/onesignal-ruby-client#10]
When I attempt to run 👇🏾 this code...

###### Ruby program
```rb
require 'dotenv/load'
require 'time'
require 'onesignal'

rest_api_key = ENV['ONESIGNAL_REST_API_KEY']
app_id = ENV['ONESIGNAL_APP_ID']

# setup authorization
OneSignal.configure do |config|
  # Configure Bearer authorization: app_key
  config.app_key = rest_api_key
end

api_instance = OneSignal::DefaultApi.new
notification = OneSignal::Notification.new({ app_id: app_id })

begin
  # Create notification
  result = api_instance.create_notification(notification)
  p result
rescue OneSignal::ApiError => e
  puts "Error when calling DefaultApi->create_notification: #{e}"
end
```

I get the following error...

###### API Error message recieved 
```
Error when calling DefaultApi->create_notification: Error message: the server returns an error
HTTP status code: 400
Response headers: {"date"=>"Mon, 07 Mar 2022 20:27:09 GMT", "content-type"=>"application/json; charset=utf-8", "status"=>"400 Bad Request", "ratelimit-limit"=>"6600", "access-control-allow-origin"=>"*", "cache-control"=>"no-cache", "referrer-policy"=>"strict-origin-when-cross-origin", "x-xss-protection"=>"1; mode=block", "ratelimit-remaining"=>"6625", "x-request-id"=>"7ceea0e7-4cdf-4555-890d-9b06fad52ec5", "access-control-allow-headers"=>"SDK-Version", "ratelimit-reference"=>"https://documentation.onesignal.com/docs/disabled-apps", "x-runtime"=>"0.012420", "x-frame-options"=>"SAMEORIGIN", "x-content-type-options"=>"nosniff", "ratelimit-reset"=>"1646684829", "x-envoy-upstream-service-time"=>"14", "vary"=>"Accept-Encoding", "cf-cache-status"=>"DYNAMIC", "expect-ct"=>"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", "server"=>"cloudflare", "cf-ray"=>"6e8611f8a9c1e02b-DFW", "alt-svc"=>"h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400"}
Response body: {"errors":["You must include which players, segments, or tags you wish to send this notification to."]}
```

###### Response headers 
```rb
Response headers: {
  "date"=>"Mon, 07 Mar 2022 20:14:39 GMT",
  "content-type"=>"application/json; charset=utf-8",
  "status"=>"400 Bad Request",
  "ratelimit-limit"=>"6600",
  "access-control-allow-origin"=>"*",
  "cache-control"=>"no-cache",
  "referrer-policy"=>"strict-origin-when-cross-origin",
  "x-xss-protection"=>"1; mode=block",
  "ratelimit-remaining"=>"6625",
  "x-request-id"=>"b8e64a6f-f0be-4e67-abdb-3afedeae777a",
  "access-control-allow-headers"=>"SDK-Version",
  "ratelimit-reference"=>"https://documentation.onesignal.com/docs/disabled-apps",
  "x-runtime"=>"0.008245",
  "x-frame-options"=>"SAMEORIGIN",
  "x-content-type-options"=>"nosniff",
  "ratelimit-reset"=>"1646684079",
  "x-envoy-upstream-service-time"=>"10",
  "vary"=>"Accept-Encoding",
  "cf-cache-status"=>"DYNAMIC",
  "expect-ct"=>"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
  "server"=>"cloudflare",
  "cf-ray"=>"6e85ffa63c1f93eb-DFW",
  "alt-svc"=>"h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400"
}
```

###### Response body
```rb
Response body: {
  "errors": [
    "You must include which players, segments, or tags you wish to send this notification to."
  ]
}
```

The error indicates I must include which players, segments, or tags I wish to send this notification to. The problem is no documentation specifying how to do this.

### Other notes

I had to change the line `config.access_token = rest_api_key` to `config.app_key = rest_api_key` because the method doesn't exist. I'm not sure about Ruby's nomenclature, but shouldn't this be an attribute? 

###### Error message when using `access_token`
```
fun-with-onesignal.rb:8:in `block in <main>': undefined method `access_token=' for #<OneSignal::Configuration:0x000000013a887fa8 @scheme="https", @host="onesignal.com", @base_path="/api/v1", @server_index=0, @server_operation_index={}, @server_variables={}, @server_operation_variables={}, @timeout=0, @client_side_validation=true, @verify_ssl=true, @verify_ssl_host=true, @params_encoding=nil, @cert_file=nil, @key_file=nil, @debugging=false, @inject_format=false, @force_ending_format=false, @logger=#<Logger:0x000000013a887df0 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000013a887cb0 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x000000013a887ad0 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @binmode=false, @mon_data=#<Monitor:0x000000013a887a08>, @mon_data_owner_object_id=260>>> (NoMethodError)
        from /Users/iamwill/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/onesignal-1.0.0.beta1/lib/onesignal.rb:69:in `configure'
        from fun-with-onesignal.rb:6:in `<main>'
``` 

I inspected the configuration object code 👇🏾 and couldn't find any mention of `access_token`, so I used `app_key`. The README should be clarified and include all details needed to get a working example. Ideally, the getting started instructions have a code sample that works. It's not a great experience reading the source to figure out how to get this to work.

https://github.com/OneSignal/onesignal-ruby-client/blob/aa6601f850f71d9a272213dd1f721757a05d99b5/lib/onesignal/configuration.rb#L14-L115

**Comment by iAmWillShepherd** [comment]
I realized I was looking at the README for the wrong branch 🤦🏾. I think it's worth adding a link to the README on `main` to the one of `pre-1.0.0` to help prevent confusion.

**Comment by iAmWillShepherd** [comment]
On second thought, maybe I didn't look at the incorrect branch 🤔? Tbh, I don't know; this is very confusing.

**Comment by iAmWillShepherd** [comment]
Quick update...

I changed the following statment `result = api_instance.create_notification(notification)` to `result = api_instance.create_notification(notification, included_segments: [ 'Active Users' ])` in response to the error message I received. 

> You must include which players, segments, or tags you wish to send this notification to

###### Updated code block
```rb
begin
  # Create notification
  result = api_instance.create_notification(notification, included_segments: ['Active Users'])
  p result
rescue OneSignal::ApiError => e
  puts "Error when calling DefaultApi->create_notification: #{e}"
end
```

I'm getting the same error. 

```
Error when calling DefaultApi->create_notification: Error message: the server returns an error
HTTP status code: 400
Response headers: {"date"=>"Tue, 08 Mar 2022 19:23:27 GMT", "content-type"=>"application/json; charset=utf-8", "status"=>"400 Bad Request", "ratelimit-limit"=>"6600", "access-control-allow-origin"=>"*", "cache-control"=>"no-cache", "referrer-policy"=>"strict-origin-when-cross-origin", "x-xss-protection"=>"1; mode=block", "ratelimit-remaining"=>"6625", "x-request-id"=>"30517370-6e97-4cc8-9493-cc420398289a", "access-control-allow-headers"=>"SDK-Version", "ratelimit-reference"=>"https://documentation.onesignal.com/docs/disabled-apps", "x-runtime"=>"0.011930", "x-frame-options"=>"SAMEORIGIN", "x-content-type-options"=>"nosniff", "ratelimit-reset"=>"1646767407", "x-envoy-upstream-service-time"=>"13", "vary"=>"Accept-Encoding", "cf-cache-status"=>"DYNAMIC", "expect-ct"=>"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", "server"=>"cloudflare", "cf-ray"=>"6e8df208d820d2a6-DFW", "alt-svc"=>"h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400"}
Response body: {"errors":["You must include which players, segments, or tags you wish to send this notification to."]}
```

FWIW, I'm following [this API doc](https://documentation.onesignal.com/reference/create-notification#send-to-segments). One thing to note is it's very confusing that I need to look at API docs for Ruby stuff. The docs make no mention of ruby and this repo doesn't indicate that people should be using API docs. I'm assuming that Ruby and HTTP are the same as a result.

**Comment by iAmWillShepherd** [comment]
> Can you elaborate a bit on this comment? I’m not sure what you mean.
> - @rgomezp 

The readme is confusing for these reasons:
* There are no docs on our site that are explicitly for Ruby
* Using the REST API docs is not the first thing I’d think to look at when I’m trying to figure out how to use the Ruby client (my perspective may be unique, but I doubt others would think to reference REST API docs when trying to figure out how to use the Ruby client)
* The repo’s readme doesn’t state that the REST API docs can be used
* My assumption is that the REST API docs are a 1:1 match to Ruby. What I mean by this is that I could copy a cURL command and paste it into one of the Ruby functions and it would just work, but after looking at one of the snippets, this is not the case

###### REST API Ruby Snippet
```rb
params = {"app_id" => "5eb5a37e-b458-11e3-ac11-000c2940e62c", 
          "contents" => {"en" => "English Message"},
          "included_segments" => ["Subscribed Users"]}
uri = URI.parse('https://onesignal.com/api/v1/notifications')
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true

request = Net::HTTP::Post.new(uri.path,
                              'Content-Type'  => 'application/json;charset=utf-8',
                              'Authorization' => "Basic NGEwMGZmMjItY2NkNy0xMWUzLTk5ZDUtMDAwYzI5NDBlNjJj")
request.body = params.as_json.to_json
response = http.request(request) 
puts response.body
```

The Ruby client doesn’t use this, so I’m not sure how REST API docs are useful for someone trying to use the Ruby client. I do understand that advanced Ruby users may be able to translate between HTTP and this client, but I don’t think most people fall into that group.

Does that make sense??
